### ISSUE TITLE
Enhancement: Some ideas for this handy app

### ISSUE THREAD

**Issue by avico78** [foxcris/appdaemon-telegrambot#2]
first, i think you done great work here ,
i find this app very useful- thanks a lot.

some things that i think could make it perfect : 

1.filtering: 
sometimes i prefer not all light/sensor/entities will be shown in telegram ,
how a filtering option can be implement in the code?

2.Adding an option to trigger automation /scripts/shell_command that define in HA,
in example , user send /automation and by the same approach u fetch all light sensors,
show automations (with an option of filtering as suggest in #1) 

3.HA version check : 
it could be very handy if  get push notification of new version and option for pull new HA image and upgrade .

4.Waze:

In my setup i define several zones which i use in waze platform ,
and by input_select i can get the time to destination ,route an etc.
so from app - if user send /waze and then present him source and destination option by the input_select and then present him summary of time to destination and route.
This could be very useful....

5.Get state of the system - cpu/storage 

hopefully u think this useful and of course feasible ...

**Comment by foxcris** [comment]
Sorry for the late response. Your idea are really good. I will think about a possiblity to extend the app to support your ideas. I think your ideas 1, 2, and can be implemented without circumstances. For option 4 i am not sure as I do not know the home-assistant integration. 
I already took a look at idea number 5 (state of the system). With home-assistant there is the system monitor integration available (https://www.home-assistant.io/integrations/systemmonitor/). I will try to set this up for my system and create a possibility to request these information. Are you using this currently? 

Certainly you are welcome to help with te improvement and create a push request for any of our ideas :-).

**Comment by foxcris** [comment]
One question regarding idea 3. Implementing a check for an availbale update shoud be easy. But how to perform an upgrade? What installation are oyu using? I am using home-assistant with docker and there is no possibility i am aware of to initiate an update without providing access to crate and run docker containers on the hosts - thats something i would not porposoe due to security.

**Comment by foxcris** [comment]
I created https://github.com/foxcris/appdaemon-telegrambot/issues/4 for idea number 5.

**Comment by avico78** [comment]
> One question regarding idea 3. Implementing a check for an availbale update shoud be easy. But how to perform an upgrade? What installation are oyu using? I am using home-assistant with docker and there is no possibility i am aware of to initiate an update without providing access to crate and run docker containers on the hosts - thats something i would not porposoe due to security.

Hi foxcris ,

Your application drive me to start learn python:)
so thanks again!

for item #1 : 
I did the following  - on app.yaml
User  <can >  add sensors by:
  sensor: light.garden_front,light.garden_back
and in code i added filtering as following:
'''
    def _cmd_state_light(self, target_id):
        all_statedict = self.get_state()
        msg = "" 
        for sensor in self.split_device_list(self.args["sensor"]):
            cur_state = self.get_state(sensor)
            friendly_name = self.friendly_name(sensor)
....
'''
*  when i think about it , we need to add this a conditional filtering ,
meaning if user define the sensor in app.yaml - so it use it as filter 
else , the program should fetch all.


regarding your question :  
I think the best way to do this is to define in HA:
in configuration.yaml - add the updater
```
updater:
```
and add sensor for current version (or do grep on config/.HA_VERSION file

```
senso
  - platform: version
    name: installed version
    source: local
   ```

next ,need to create automation which check if current version is < latest one,
this is how i implement in HA

```
  - platform: template
    sensors:
      upgrade_ha:
        friendly_name: "New HA version"
        value_template: >
             {%- if state_attr('binary_sensor.updater', 'newest_version') != states.sensor.installed_version.state -%}
               Yes
             {%- else -%}
               No
             {%- endif -%}
        icon_template: >-
          {%- if state_attr('binary_sensor.updater', 'newest_version') != states.sensor.installed_version.state -%}
            mdi:alert-box
          {% else %}
            mdi:approval
          {% endif %}
```
Next stop is to call command for pull new version
something like : 
sudo docker-compose -f /home/docker-compose.yaml pull homeassistant
stop HA docker
and run it with up -d again .
of course it will required the user to predefine the docker-compose path ,
I also trying to do things based ur approach - but there a learning curve as im not really familiar with python.

**Comment by avico78** [comment]
I'd like to share 2 more things came up with:


1.I start to think that for example "show list of state" and other features can be define by the parameters in app.yaml,
as all "state of" lights,sensor,automation and more or the same fetching by same approach.
so it can bring for flexibility to the user ,i believe it will minimize the code as functions will be more generic and it bring the app to higher level as real platform for HA.

please refer to "Passing Arguments to Apps" :
https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html

Interesting to know what you think about this approach ....


2."cosmetic" -
I think it will look better if the menu show always with buttons and nice graphic,
I manage to display the all menu with buttons but got stuck with how to relate each button to method...
see:

````
  if command == "/help":
        
            msg = "The following commands are available:\n"
           keyboard = []
           assign_key = []
## Menu display as button - but not sure how to assign menu- maybe break menu as separate function ??
           keyboard.append([("Menu",f"/menu")])
           for command in self._commanddict:
                desc = f'{self._commanddict.get(command).get("desc")}'
                method_str = f'/self.{self._commanddict.get(command).get("method").__name__}'
##Not sure how to assign the method to button 
                keyboard.append([(desc,method_str)])                
           str_keyboard = ', '.join(map(str, keyboard))
           self._call_service(msg,user_id,keyboard)
  ..... 

    def _call_service (self, msg ,target_id , keyboard = []):
        self.log(keyboard)
        self.call_service(
            "telegram_bot/send_message",
            target=target_id,
            message=self._escape_markdown(msg),
            inline_keyboard=keyboard
        )  
````
wish i could be more helpful with coding and actually be your right hand man here as i really like this project and find it very useful .
i will do my best but it's taking time .

**Comment by foxcris** [comment]
i just released verison 1.0 which is implementing idea 1, 5 and a part of number 3.
Filtering is done via app parameters. 

Regarding the option to install/upgrade to a new version:
What setup are you running? I have different docker containers running for appdaemon and home-assistant. Regarding security i do not think its the best idae to mount the docker socket into the appdaemon container to upgrade the home-assistant container. The problem is, that if we have an security issue in the bot some one could run abritary commands on the docker socket and create/change containers. 

Currently my containers are automatically updated using watchtower. Isn't that an option for you?

Regarding your last message:
1. For filtering i am using the app parameters. Everything else was written especially the way that you do not need to configure the "app" for each entity. I did't want to explicitly keep the configuration of the the appdaemon telegrambot app and home-assistant in sync. So per default everything of the specifc domain (cover, climate, ...) is used.

2. Nice Idea. I think that should be possible. I started without the buttons, because i did'nt know of them at the beginning. I will take a look at this.

One suggestion: Lets try to seperate differnt enhandements and ideas into different issues ok? This would ease the handling of them.

Please give Version 1.0 a try an report back if the filtering system fulfill your needs. Take care that you update your app.yaml with the update.

**Comment by foxcris** [comment]
@avico78 : Can you provide me with your waze setup in https://github.com/foxcris/appdaemon-telegrambot/issues/8?

**Comment by avico78** [comment]
> @avico78 : Can you provide me with your waze setup in #8?

#8 updated

**Comment by foxcris** [comment]
i think we have seperate tickets for each of the request now. Thus i close this one.
